### ISSUE TITLE
ppc64le build for v1.26.0 is missing

### ISSUE THREAD

**Issue by maresb** [conda-forge/dasel-feedstock#7]
### Comment:

This affects only people using the ppc64le platform, which should be a fairly small number of users.

There seems to be a transient issue with the ppc64le pipeline on Travis CI, so v1.26.0 cannot be built at this time. On the [advice](https://gitter.im/conda-forge-ppc64le/Lobby?at=62cbf41d3bbb384889360904) of @jakirkham I have merged anyways in order to publish the other builds.

Hopefully the issue will be resolved before v1.27.0 comes out, and things will proceed normally from there. In the meantime, v1.25.0 is still available.

**Comment by maresb** [comment]
After I merged, all of the builds (incl. ppc) were successful ... so either I got lucky, or the problem is fixed, or there's something different with the final build.

**Comment by jakirkham** [comment]
Glad to hear it resolved itself 😀
